version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}interviewsolution
    container_name: backend-net
    build:
      context: .
      dockerfile: InterviewSolution/Dockerfile
  

  client:
    image: client
    container_name: frontend-client
    build:
      context: ./client-react
      dockerfile: Dockerfile

  database:
    image: postgres:14.4-alpine
    container_name: database-postgres
    restart: always


  proxy:
    image: nginx:mainline
    container_name: reverse-proxy-nginx